import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, '..');
const docsRoot = path.resolve(appDir, '..');
const outputDir = path.join(appDir, 'src');
const outputFile = path.join(outputDir, 'generated-content.js');

const chapterDirs = (await readdir(docsRoot, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && /^\d{2}-/.test(entry.name))
  .sort((a, b) => a.name.localeCompare(b.name));

function frontmatterValue(markdown, key) {
  const match = markdown.match(new RegExp(`^${key}:\\s*["']?(.+?)["']?\\s*$`, 'm'));
  return match?.[1]?.trim() || '';
}

function titleFrom(markdown, fallback) {
  const title = frontmatterValue(markdown, 'title');
  if (title) return title;
  return markdown.match(/^#\s+(.+)$/m)?.[1]?.replace(/^\S+\s+/, '').trim() || fallback;
}

function stripMarkdown(markdown) {
  return markdown
    .replace(/^---[\s\S]*?---\s*/m, '')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^\s*>\s?/gm, '')
    .replace(/[*_`]/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function extractCode(markdown) {
  return markdown.match(/```(?:csharp|cs|c#|dotnet)?\s*\n([\s\S]*?)```/i)?.[1]?.trim() || '';
}

function extractDiagram(markdown) {
  return markdown.match(/```mermaid\s*\n([\s\S]*?)```/i)?.[1]?.trim() || '';
}

const lessons = [];
for (const chapterDir of chapterDirs) {
  const files = (await readdir(path.join(docsRoot, chapterDir.name)))
    .filter((file) => file.endsWith('.md') && file.toLowerCase() !== 'readme.md')
    .sort();
  for (const file of files) {
    const relativePath = path.join(chapterDir.name, file).replaceAll('\\', '/');
    const markdown = await readFile(path.join(docsRoot, relativePath), 'utf8');
    const cleanText = stripMarkdown(markdown);
    lessons.push({
      chapterId: chapterDir.name.slice(0, 2),
      file: relativePath,
      title: titleFrom(markdown, file.replace('.md', '')),
      summary: cleanText.slice(0, 1200),
      code: extractCode(markdown),
      diagram: extractDiagram(markdown),
      sourceWords: cleanText.split(/\s+/).filter(Boolean).length,
    });
  }
}

await mkdir(outputDir, { recursive: true });
await writeFile(outputFile, `// Generated by scripts/generate-content.mjs. Do not edit manually.\nexport const lessonSources = ${JSON.stringify(lessons, null, 2)};\n`, 'utf8');
console.log(`Generated ${lessons.length} lessons from Markdown files.`);
